version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./prisma-data:/var/lib/postgresql/data
  yanb-web:
    image: pcheebs/yanb-web:1.0.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      YANB_GRAPHQL_API: https://budget.philchang.me:4000
      RECAPTCHA_SITE_KEY: 6LckQ9cUAAAAAA6os_dvtJKfvQfgS5Yd0Z_NQSFW
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  yanb-graphql:
    image: pcheebs/yanb-graphql:1.0.0
    restart: always
    ports:
      - "4000:4000"
    links:
      - prisma
    environment:
      PRISMA_API: http://prisma:4466
      DOMAIN: budget.philchang.me
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
