name: Build and Push YANB Docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Navigate to yanb-web folder
      run: cd web
    - name: Build yanb-web tagged
      run: docker build . --file Dockerfile --tag pcheebs/yanb-web:${{steps.vars.outputs.tag}}
    - name: Push yanb-web tagged
      run: docker push pcheebs/yanb-web:${{steps.vars.outputs.tag}}
    - name: Navigate to yanb-web folder
      run: cd ../prisma-server
    - name: Build yanb-graphql tagged
      run: docker build . --file Dockerfile --tag pcheebs/yanb-graphql:${{steps.vars.outputs.tag}}
    - name: Push yanb-graphql tagged
      run: docker push pcheebs/yanb-graphql:${{steps.vars.outputs.tag}}
